services:
  - type: web
    name: pedro-lichtnow-site
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pedro-lichtnow-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: pedro-lichtnow-db
    databaseName: pedro_lichtnow
    user: pedro_lichtnow
    plan: free 